name: Release Workflow
on:
  push:
    tags:
      - '*'
jobs:
  build:
    if: github.event.base_ref == 'refs/heads/master' && github.repository == 'mirkosertic/flight-recorder-starter'
    environment: ci
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"
      - run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - run: |
          echo "on a tag -> set pom.xml <version> to ${{steps.tag.outputs.tag}}"
          mvn --settings .mvn/settings.xml org.codehaus.mojo:versions-maven-plugin:set -DnewVersion=${{steps.tag.outputs.tag}}
          mvn --no-transfer-progress --batch-mode --settings .mvn/settings.xml clean javadoc:jar deploy -P signed
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
